# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

reconstruct3 <- function(m_lower, diag = TRUE, symmetric = TRUE) {
    .Call('_SimulateurSaMARE_reconstruct3', PACKAGE = 'SimulateurSaMARE', m_lower, diag, symmetric)
}

